language: python
python: "2.7"

install: pip install tox

before_script:
    - sudo update-alternatives --install /bin/sh sh /bin/bash 100
    - git clone --depth 1 https://github.com/genome/ptero-common.git

env:
    global:
        - PTERO_COMMON_HOME=./ptero-common

script: tox

after_script:
    - ps -efl > var/log/ps.out
    - bash -c 'for f in var/log/*; do echo; echo "============================================"; echo $f; echo "============================================"; cat $f; done'

after_success:
    - pip install coveralls
    - coveralls
